{% set name = "ocaml-zarith" %}
{% set version = "1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ocaml/Zarith/archive/release-{{ version }}.tar.gz
  sha256: 5db9dcbd939153942a08581fabd846d0f3f2b8c67fe68b855127e0472d4d1859

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
  host:
    - ocaml
    - ocaml-findlib
    - gmp
  run:
    - {{ pin_compatible("ocaml", max_pin="x.x") }}

test:
  requires:
    - ocaml-findlib
  commands:
    - ocamlfind -query zarith
    - test -f $PREFIX/lib/ocaml/site-lib/zarith/zarith.h
    - test -f $PREFIX/lib/ocaml/site-lib/zarith/zarith.cma

about:
  home: https://github.com/ocaml/Zarith
  license: LGPL-2.0-only
  license_file: LICENSE
  summary: The Zarith library implements arithmetic and logical operations over arbitrary-precision integers and rational numbers.

extra:
  recipe-maintainers:
    - isuruf
