{% set name = "ocaml-zarith" %}
{% set version = "1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ocaml/Zarith/archive/release-{{ version }}.tar.gz
  sha256: cc32563c3845c86d0f609c86d83bf8607ef12354863d31d3bffc0dacf1ed2881

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - ocaml
    - ocaml-findlib
    - gmp
  run:
    - {{ pin_compatible("ocaml", max_pin="x.x") }}

test:
  requires:
    - ocaml-findlib
  commands:
    - ocamlfind -query zarith
    - test -f $PREFIX/lib/ocaml/site-lib/zarith/zarith.h
    - test -f $PREFIX/lib/ocaml/site-lib/zarith/zarith.cma

about:
  home: https://github.com/ocaml/Zarith
  license: LGPL-2.0-only
  license_file: LICENSE
  summary: The Zarith library implements arithmetic and logical operations over arbitrary-precision integers and rational numbers.

extra:
  recipe-maintainers:
    - isuruf
